### ISSUE TITLE
Can't distinguish between nil/invalid API key and failed search

### ISSUE THREAD

**Issue by armandofox** [ahmetabdi/themoviedb#22]
In 0.0.14, attempting to use the API with a nil or invalid API key caused an exception (a weird one, having to do with a failed 'gsub', but at least you knew something was wrong.)

In 0.0.17, the following scenarios give identical results:

- Call Movie.detail(x) with valid API key, where x is a nonexistent TMDb resource id
- Call Movie.detail(x) with INVALID API key, where x is a nonexistent TMDB resource id
- Call Movie.detail(x) with INVALID API key, where x is a VALID existing TMDB resource id
All three calls return a Movie resource whose attributes are all nil.

This is bad for programmers because you can't distinguish between an "invalid API key"  error and an error due to supplying a nonexistent ID.

**Comment by ahmetabdi** [comment]
Solved thanks @armandofox
