### ISSUE TITLE
Thread Safe language changing for Requests

### ISSUE THREAD

**Issue by Jeehut** [ahmetabdi/themoviedb#33]
I want to make calls in the background using the sidekiq gem so I need a thread-safe way to change the language for single requests. Currently there's no request-wide language setting, only the global `Tmdb::Api.language("de")` setting which – I believe – is not thread-safe. Or is it?

If not, it would be great to have a thread-safe way of making language-specific requests. E.g. the following two requests could be run at the same time in different threads of sidekiq and I don't want this to result in the wrong languages at the wrong place:

``` ruby
Tmdb::Api.language("de")
Tmdb::Movie.find("batman")
```

``` ruby
Tmdb::Api.language("fr")
Tmdb::Movie.find("batman")
```

**Comment by dankimio** [comment]
Hi Cihat! It should be thread-safe for single requests. Have you encountered any issues? Perhaps, setting language before each use would resolve this. Feel free to reopen the issue if it ever resurfaces.

**Comment by Jeehut** [comment]
It's been more than 10 years since I asked the question, so I don't even remember the context. 😅 I moved on long ago. I'm no longer using any 3rd party dependencies for any APIs anymore. So I can't tell if there's an issue in the lib.

But thanks for taking the time!
