### ISSUE TITLE
Hashugar

### ISSUE THREAD

**Issue by kostyadubinin** [ahmetabdi/themoviedb#35]
What's the point of using Hashugar? It doesn't look like a mature library.

```ruby
h1 = { a: 5, b: 6 }.to_hashugar
h2 = { a: 5, b: 6 }.to_hashugar
h1 == h2 # => false
```

**Comment by finishingmove** [comment]
Hello @ahmetabdi . Thank you for a great wrapper library, but I too do not understand why the use of Hashugar. 

Hashugar returns a construct such as:

    "created_by": [
            {
                "table": {
                    "id": 1745,
                    "name": "Gene Roddenberry",
                    "profile_path": "/9WMyiCTdtBEdx1JUCavoFiDl7wd.jpg"
                },
                "table_with_original_keys": {
                    "id": 1745,
                    "name": "Gene Roddenberry",
                    "profile_path": "/9WMyiCTdtBEdx1JUCavoFiDl7wd.jpg"
                }
            }
        ]

where I would expect simply:

    "created_by": [
                {
                    "id": 1745,
                    "name": "Gene Roddenberry",
                    "profile_path": "/9WMyiCTdtBEdx1JUCavoFiDl7wd.jpg"
                }
        ]

That's the JSON representation, here's the Ruby one, just for the record:

    "created_by"=>
    [#<Hashugar:0x00000003613d68
      @table={"id"=>1745, "name"=>"Gene Roddenberry", "profile_path"=>"/9WMyiCTdtBEdx1JUCavoFiDl7wd.jpg"},
      @table_with_original_keys={"id"=>1745, "name"=>"Gene Roddenberry", "profile_path"=>"/9WMyiCTdtBEdx1JUCavoFiDl7wd.jpg"}>]

This is horrible. Is there a way to just use plain ruby objects here?

**Comment by ahmetabdi** [comment]
Yes there is go here https://github.com/ahmetabdi/themoviedb/blob/master/lib/themoviedb/search.rb#L76 edit the response and submit a PR and I'll accept it.

**Comment by finishingmove** [comment]
How would that affect the rest of this commit? https://github.com/ahmetabdi/themoviedb/commit/f9a3c9b7e64f29f9eb62b4553ba4c5f4e6f48ebc

For now, I have resorted to using version 0.0.22 of the library that works great for my needs.

**Comment by ahmetabdi** [comment]
https://github.com/ahmetabdi/themoviedb/commit/dd625df6bc276a95a5e82922cf47b194e8bffc1a

**Comment by itsdn** [comment]
We can close the issue now :)

**Comment by ahmetabdi** [comment]
Yep :dancer:
