### ISSUE TITLE
0.0.25 Introduces Breaking Changes

### ISSUE THREAD

**Issue by maddox** [ahmetabdi/themoviedb#40]
I understand that this gem isn't maintained anymore, but I implore you to reject the `0.0.25` published gem, and replace it with a `0.1.0` version.

The reason is that `0.0.25` introduces a huge breaking change with the API by removing hashuger thus changing the api from:

```ruby
@movie.backdrops
```
to

```ruby
@movie['backdrops']
```

Bundler has a certain expectation that it can bump the patch version of a gem without expecting any major changes. Most developers have this expectation as well and regularly update their gems this way. By doing this, this would install a version of this gem that would have serious compatibility consequences. If it were `0.1.0`, it would not get installed without direct effort by the developer.

Again, I understand that this gem has become unmaintained, but bumping it to a `0.1.0` before doing this would be, in my opinion, a more responsible thing to do.

**Comment by ahmetabdi** [comment]
I understand that this could cause problems for people so I've yanked the 0.0.25 gem from rubygems and have pushed a version 0.1.0 thank you! My knowledge of when to update patch versions has improved :)

**Comment by maddox** [comment]
:thumbsup::thumbsup::thumbsup:
