### ISSUE TITLE
Return native resources

### ISSUE THREAD

**Issue by itsdn** [ahmetabdi/themoviedb#45]
Some methods like `Tmdb::Movie.search` return a collection of `Tmdb::Movie` objects. However, there are ones that return hashes (`Tmdb::Movie.popular`, `Tmdb::Movie.now_playing`, etc.). Is there a reason these methods return pure hashes? If not, I can submit a pull request with these changes.

**Comment by ahmetabdi** [comment]
No particular reason I started working on a complete rewrite of this gem a few months ago that I haven't got around to working on much that would make everything constant with more feature, happy for a PR on current version.
